os: Visual Studio 2017
version: 5.0.0-beta-{build}
configuration: Release
cache:
  - packages
before_build:
  - dotnet restore
build:
  project: JustSaying.sln
  parallel: true
  verbosity: minimal
pull_requests:
  do_not_increment_build_number: true
test_script:
  - ps: $wc = New-Object 'System.Net.WebClient'
  - dotnet run --project .\JustSaying.AwsTools.UnitTests\JustSaying.AwsTools.UnitTests.csproj
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
  - dotnet run --project .\JustSaying.Messaging.UnitTests\JustSaying.Messaging.UnitTests.csproj
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
  - dotnet run --project .\JustSaying.UnitTests\JustSaying.UnitTests.csproj
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\JustSaying.UnitTests\TestResult.xml))
after_build:
- dotnet pack .\JustSaying\JustSaying.csproj -o artifacts --no-build
- dotnet pack .\JustSaying.AwsTools\JustSaying.AwsTools.csproj -o artifacts --no-build
- dotnet pack .\JustSaying.Messaging\JustSaying.Messaging.csproj -o artifacts --no-build
- dotnet pack .\JustSaying.Models\JustSaying.Models.csproj -o artifacts --no-build
artifacts:
- path: '**\*.nupkg'
notifications:
- provider: HipChat
  room: 'Eng :: Open Source'
  auth_token:
    secure: eJWABMRPoyfEF9iLzFaTcUEqTc7/64v0FtS1qQe4yhs=
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
- provider: Webhook
  url: https://webhooks.gitter.im/e/1d5903ab716f417802d0
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
deploy:
- provider: NuGet
  api_key:
    secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7
  artifact: /.*nupkg/
  on:
    APPVEYOR_REPO_TAG: true
